# .pre-commit-config.yaml
minimum_pre_commit_version: "3.5.0"

# Don’t waste time in build outputs or deps
exclude: |
  ^(build/|
    cpp/build/|
    api/.venv/|
    web/.next/|
    web/node_modules/)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Python formatting (api/, tests/)
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        files: ^(api|tests)/

  # Python lint (fast, with autofix)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(api|tests)/
      - id: ruff-format
        files: ^(api|tests)/

  # C/C++ formatting (src + include)
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.8
    hooks:
      - id: clang-format
        files: ^cpp/(src|include)/.*\.(c|cc|cpp|cxx|h|hpp|hh)$
        # If you add a .clang-format at repo root, it will be used automatically.

  # Web formatting (Next.js sources)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^web/src/.*\.(ts|tsx|js|jsx|json|css|md)$
        args: [--write]
